function names = get_feature_names_20()
    names = { ...
        'Ego_Vel_X', 'Ego_Vel_Y', ...
        'Ego_Acc_X', 'Ego_Acc_Y', ...
        'Ego_Jerk_X', 'Ego_Jerk_Y', ...
        'Rel_Pos_X', 'Rel_Pos_Y', ...
        'Rel_Vel_X', 'Rel_Vel_Y', ...
        'Cos_Yaw', 'Sin_Yaw', ...
        'Inverse_TTC', ...
        'Rel_Kinetic_Energy', ...
        'Proximity_Potential', ...
        'NPC_Aggressiveness', ...
        'Env_Friction_Est', ...
        'Env_Time_Cyclic_Sin', 'Env_Time_Cyclic_Cos', ...
        'Ego_Path_Curvature'
    };
end